{% set name = "testtools" %}
{% set version = "2.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/testtools-{{ version }}.tar.gz
  sha256: 5be5bbc1f0fa0f8b60aca6ceec07845d41d0c475cf445bfadb4d2c45ec397ea3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}

test:
  imports:
    - testtools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/testing-cabal/testtools
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Extensions to the Python standard library unit testing framework
  dev_url: https://github.com/testing-cabal/testtools
  doc_url: https://testtools.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - BastianZim
