{% set name = "testtools" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/testtools-{{ version }}.tar.gz
  sha256: eec326f4275e6a55e5540302d01a0ae0a9e48991d7aade38a5c8ed093c37993a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pbr
    - pip
    - python >=3.6
  run:
    - extras >=1.0.0
    - fixtures >=1.3.0
    - pbr >=0.11
    - python >=3.6

test:
  imports:
    - testtools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/testing-cabal/testtools
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Extensions to the Python standard library unit testing framework
  dev_url: https://github.com/testing-cabal/testtools
  doc_url: https://testtools.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - BastianZim
