{% set name = "testtools" %}
{% set version = "2.5.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "57c13433d94f9ffde3be6534177d10fb0c1507cc499319128958ca91a65cb23f" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - pbr >=0.11

  run:
    - python
    - pbr >=0.11

test:
  imports:
    - testtools

about:
  home: https://github.com/testing-cabal/testtools
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Extensions to the Python standard library unit testing framework
  dev_url: https://github.com/testing-cabal/testtools
  doc_url: https://testtools.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
